<?php
namespace Property\Classes;

class PropertyClass
{
	public static $project_fields = [
		'id'=>'ID',
		'project_type'=>'Project Type',
		'proj_property_type'=>'Project Property Type',
		'project_name'=>'Project Name',
		'old_project_name'=>'Old Project Name',
		'chinese_name'=>'Chinese Name',
		'all_number'=>'All Number',
		'street_name'=>'Street Name',
		'total_units'=>'Total Units',
		'total_available_units'=>'Available Total Units',

		'available_date'=>'Available Date',
		'detached_house'=>'Detached House',
		'semi_detached_house'=>'Semi-Detached House',
		'terrace_house'=>'Terrace House',
		'apt_condo'=>'Apt/Condo',
		'shops'=>'Shops',
		'childcare'=>'Childcare',
				
		'old_total_units'=>'Total Units Sold',
		'unit_type'=>'Unit Type',
		'available_unit_type'=>'Available Unit Type',
		'date_avail_unit_updated'=>'Date when Available Unit Type is updated',
		'property_type'=>'Property Type',
		'tenure'=>'Tenure',
		'top_year'=>'TOP Yr',
		'top_month'=>'TOP Mth',
		'top_date'=>'TOP Day',
		'district'=>'District',
		'planning_region'=>'Planning Region',
		'planning_area'=>'Planning Area',
		'low_psf'=>'Low psf',
		'median_psf'=>'Median psf',
		'high_psf'=>'High psf',
		'status'=>'Status',
		'status_date'=>'Date',
		'status2'=>'Status2',
		'status2_date'=>'Date2',
		'sale_price'=>'Sale Price in Millions',
		'psf_ppr'=>'psf ppr',
		'psm_ppr'=>'psm ppr',
		'gls_sold_date'=>'Enbloc or GLS Sold Date',
		'low_millions'=>'Low Millions',
		'high_millions'=>'High Millions',
		'tender_agency'=>'Tender Agency',
		'stb_application_date'=>'STB Appln Date',
		'stb_approval_date'=>'STB Approval Date',
		'completion_date'=>'Completion Date',
		'vacant_possession_date'=>'Vacant Possession Date',
		'successful_tenderer'=>'Successful tenderer',
		'no_transactions'=>'Number of Transactions',
		'transaction_month'=>'Transaction Month',
		'rental_low_psf_pm'=>'Rental Low psf pm',
		'rental_median_psf_pm'=>'Rental Median psf pm',
		'rental_high_psf_pm'=>'Rental High psf pm',
		'no_of_rentals'=>'Number of Rentals',
		'rental_period'=>'Rental Per Quarter',
		'original_top'=>'Original TOP',
		'mrt'=>'MRT LRT',
		'mrt_distance_km'=>'Distance (km)',
		'primary_school_within_1km'=>'Primary School within 1km',
		'highest_flr'=>'Highest Flr',
		'site_area_sqft'=>'Site Area sqft',
		'site_area_sqmt'=>'Site Area sqm',
		'plot_ratio'=>'Plot Ratio',
		'gfa_sqft'=>'GFA sqft',
		'gfa_sqmt'=>'GFA sqm',
		'non_residential_area_sqft'=>'Non Residential Area sqft',
		'non_residential_area_sqm'=>'Non Residential Area sqm',
		'office_sqft'=>'Office sqft',
		'office_sqm'=>'Office sqm',
		'retail_sqft'=>'Retail sqft',
		'retail_sqm'=>'Retail sqm',
		'factory_sqft'=>'Factory sqft',
		'factory_sqm'=>'Factory sqm',
		'warehouse_sqft'=>'Warehouse sqft',
		'warehouse_sqm'=>'Warehouse sqm',
		'developer'=>'Developer Owner',
		'marketing_agency'=>'Mkting Agency',
		'project_ref_no'=>'Project Ref Number',
		'approved_date'=>'Date Approved',
		'locality'=>'Locality',
		'top_no'=>'TOP Number',
		'issue_date'=>'Date Issued',
		'floor_area'=>'Floor Area',
		'cost'=>'Cost',
		'development_status'=>'Development Status',
		'ds_date'=>'DS Date',
		'land_type'=>'Land Type',
		'sector'=>'Sector',
		'date_updated'=>'Date Spreadsheet Updated',
		'description'=>'Description',
	];
	public static $project_per_project_fields = [
		'project_id'=>'Project ID',
		'project_name'=>'Project Name',
		'project_type'=>'Project Type',
		'proj_property_type'=>'Project Property Type',
		'area_sqmt'=>'Area sqm',
		'area_sqft'=>'Area sqft',
		'unit_type'=>'Unit Type',
		'low_price'=>'Low Price',
		'median_price'=>'Median Price',
		'high_price'=>'High Price',
		'no_of_units'=>'Number of units',
		'units_sold'=>'Units sold',
		'units_unsold'=>'Units unsold',
		'share_value'=>'Share Value',
		'share_amount'=>'Share Amt',
		'mtce_fee'=>'Mtce Fee',
	];

	public static $project_detail_fields = [
		'project_id'=>'Project Name',
		'address'=>'Address',
		'sale_date'=>'Sale Date',
		'project_type'=>'Project Type',
		'proj_property_type'=>'Project Property Type',
		'unit_type'=>'Unit Type',
		'no_units_per_transaction'=>'No. of units per transaction',
		'area_type'=>'Type of Area',
		'transacted_price'=>'Transacted Price',
		'nett_price'=>'Nett Price',
		'unit_price_psm'=>'Unit Price psm',
		'unit_price_psf'=>'Unit Price psf',
		'property_type'=>'Property Type',
		'property2_type'=>'Property Type 2',
		'tenure'=>'Tenure',
		'tenure2'=>'Tenure 2',
		'top_year'=>'TOP Yr',
		'type_of_sale_per_trxn'=>'Type of Sale Per Transaction',
		'hdb_pte'=>'HDB or Pte',
		'district'=>'District',
		'postal_sector'=>'Postal Sector',
		'postal_code'=>'Postal Code',
		'planning_region'=>'Planning Region',
		'planning_area'=>'Planning Area',
		'number'=>'Number',
		'street_name'=>'Street Name',
		'level'=>'Level',
		'stack'=>'Stack',
		'type'=>'Type',
		'area_sqm'=>'Area sqm',
		'area_sqf'=>'Area sqft',
		'built_area_per_sqft'=>'BuiltUp area sqft',
		'share_value'=>'Share Value',
	];

	public static $project_detail_display_fields = [
		'Project Type'=> ['project_type'],
		'Project Property Type' => ['proj_property_type'],
		'Project Name' => ['project_id'],
		'Complete Address' => ['address'],
		'Address' => ['number','street_name','level','stack'],
		'Sale Date' => ['sale_date'],
		'Unit Type' => ['unit_type','no_units_per_transaction'],
		'Type of Area' => ['area_type'],
		'Transacted Price' => ['transacted_price'],
		'Nett Price' => ['nett_price'],
		'Unit Price psm/psf' => ['unit_price_psm','unit_price_psf'],
		'Property Type / Type 2' => ['property_type','property2_type'],
		'Tenure / Tenure 2' => ['tenure', 'tenure2'],
		'TOP Yr' => ['top_year'],
		'Type of Sale Per Transaction' => ['type_of_sale_per_trxn'],
		'Type' => ['type'],
		'HDB or Pte' => ['hdb_pte'],
		'District / Planning Area' => ['district','planning_area'],
		'Postal Code / Postal Sector' => ['postal_code','postal_sector'],
		'Planning Region' => ['planning_region'],
		'Area sqm / sqft' => ['area_sqm','area_sqf'],
		'BuiltUp area sqft' => ['built_area_per_sqft'],
		'Share Value' => ['share_value']
	];

	public static $project_display_fields = [
		'Project Name' => ['project_name','chinese_name'],
		'Developer' => ['developer'],
		'Project Description' => ['description'],
		'District / Planning Area' => ['district', 'planning_area'],
		'Address' => ['all_number','street_name'],
		'Tenure' => ['tenure'],
		'Site Area sqft / sqm' => ['site_area_sqft','site_area_sqmt'],
		'Total Units' => ['total_units'],
		'Nearest MRT / Distance in km' => ['mrt','mrt_distance_km'],
		'Primary School within 1km' => ['primary_school_within_1km'],
		'TOP' => ['top_year','top_month','top_date'],
		'Property Type' => ['property_type'],
		'Unit Type' => ['unit_type'],
		'Old Project Name' => ['old_project_name'],
		'Project Type' => ['project_type'],
		'Project Property Type' => ['proj_property_type'],
		'Previous or Next Project Total Units' => ['old_total_units'],
		'Available Unit Type' => ['available_unit_type','date_avail_unit_updated'],

		'Available date' => ['available_date'],
		'House Property' => ['detached_house','semi_detached_house','terrace_house'],
		'House Property2' => ['apt_condo','shops','childcare'],

		'Status' => ['status','status_date'],
		'Status2' => ['status2','status2_date'],
		'Median psf' => ['median_psf'],
		'Low psf' => ['low_psf'],
		'High psf' => ['high_psf'],
		'Number of Transactions' => ['no_transactions'],
		'Transaction Month' => ['transaction_month'],
		'Highest Flr' => ['highest_flr'],
		'Plot Ratio' => ['plot_ratio'],
		'GFA sqft / sqm' => ['gfa_sqft','gfa_sqmt'],
		'Non Residential Area sqft / sqm' => ['non_residential_area_sqft','non_residential_area_sqm'],
		'Office sqft / sqm' => ['office_sqft','office_sqm'],
		'Retail sqft / sqm' => ['retail_sqft','retail_sqm'],
		'Factory sqft / sqm' => ['factory_sqft','factory_sqm'],
		'Warehouse sqft / sqm' => ['warehouse_sqft','warehouse_sqm'],
		'Mkting Agency' => ['marketing_agency'],
		'Project Ref Number' => ['project_ref_no','approved_date'],
		'Locality' => ['locality'],
		'TOP Number' => ['top_no','issue_date'],
		'Floor Area' => ['floor_area'],
		'Cost' => ['cost'],
		'Development Status' => ['development_status','ds_date'],
		'Land Type' => ['land_type'],
		'Sector' => ['sector'],
		'Sale Price in Millions' => ['sale_price'],
		'psf ppr / psm ppr' => ['psf_ppr','psm_ppr'],
		'Enbloc or GLS Sold Date' => ['gls_sold_date'],
		'Low Millions' => ['low_millions'],
		'High Millions' => ['high_millions'],
		'Tender Agency' => ['tender_agency'],
		'STB Appln Date' => ['stb_application_date'],
		'STB Approval Date' => ['stb_approval_date'],
		'Completion Date' => ['completion_date'],
		'Vacant Possession Date' => ['vacant_possession_date'],
		'Successful tenderer' => ['successful_tenderer'],
		'Original TOP' => ['original_top'],
		'Rental Low psf pm' => ['rental_low_psf_pm'],
		'Rental Median psf pm' => ['rental_median_psf_pm'],
		'Rental High psf pm' => ['rental_high_psf_pm'],
		'Number of Rentals' => ['no_of_rentals'],
		'Rental Per Quarter' => ['rental_period'],
		'Date Spreadsheet Updated' => ['date_updated'],
	];

	/**
	 * Change the order of an associated array, moving by key before another
	 *
	 * @param array $arr
	 * @param string $key
	 * @param string $before
	 * @return array
	 *///$arr,$find,$move
	public static function moveKeyBefore(array $arr, string $find, string $move)
	{
		if(!isset($arr[$find]) || !isset($arr[$move])){
        	return $arr;
    	}else{
	        $elem=[$move=>$arr[$move]];
	        $start=array_splice($arr,0,array_search($find,array_keys($arr)));
	        return $start+$elem+$arr;
	    }
	}

	public static $mrt_stations = [
			        ['code' => 'NS1','en' => 'Jurong East'],
			        ['code' => 'NS2','en' => 'Bukit Batok'],
			        ['code' => 'NS3','en' => 'Bukit Gombak'],
			        ['code' => 'NS4','en' => 'Choa Chu Kang'],
			        ['code' => 'NS5','en' => 'Yew Tee'],
			        ['code' => 'NS7','en' => 'Kranji'],
			        ['code' => 'NS8','en' => 'Marsiling'],
			        ['code' => 'NS9','en' => 'Woodlands'],
			        ['code' => 'NS10','en' => 'Admiralty'],
			        ['code' => 'NS11','en' => 'Sembawang'],
			        ['code' => 'NS13','en' => 'Yishun'],
			        ['code' => 'NS14','en' => 'Khatib'],
			        ['code' => 'NS15','en' => 'Yio Chu Kang'],
			        ['code' => 'NS16','en' => 'Ang Mo Kio'],
			        ['code' => 'NS17','en' => 'Bishan'],
			        ['code' => 'NS18','en' => 'Braddell'],
			        ['code' => 'NS19','en' => 'Toa Payoh'],
			        ['code' => 'NS20','en' => 'Novena'],
			        ['code' => 'NS21','en' => 'Newton'],
			        ['code' => 'NS22','en' => 'Orchard'],
			        ['code' => 'NS23','en' => 'Somerset'],
			        ['code' => 'NS24','en' => 'Dhoby Ghaut'],
			        ['code' => 'NS25','en' => 'City Hall'],
			        ['code' => 'NS26','en' => 'Raffles Place'],
			        ['code' => 'NS27','en' => 'Marina Bay'],
			        ['code' => 'NS28','en' => 'Marina South Pier'],
			        ['code' => 'CG1','en' => 'Expo'],
			        ['code' => 'CG2','en' => 'Changi Airport'],
			        ['code' => 'EW1','en' => 'Pasir Ris'],
			        ['code' => 'EW2','en' => 'Tampines'],
			        ['code' => 'EW3','en' => 'Simei'],
			        ['code' => 'EW4','en' => 'Tanah Merah'],
			        ['code' => 'EW5','en' => 'Bedok'],
			        ['code' => 'EW6','en' => 'Kembangan'],
			        ['code' => 'EW7','en' => 'Eunos'],
			        ['code' => 'EW7','en' => 'Eunos'],
			        ['code' => 'EW8','en' => 'Paya Lebar'],
			        ['code' => 'EW9','en' => 'Aljunied'],
			        ['code' => 'EW10','en' => 'Kallang'],
			        ['code' => 'EW11','en' => 'Lavender'],
			        ['code' => 'EW12','en' => 'Bugis'],
			        ['code' => 'EW13','en' => 'City Hall'],
			        ['code' => 'EW14','en' => 'Raffles Place'],
			        ['code' => 'EW15','en' => 'Tanjong Pagar'],
			        ['code' => 'EW16','en' => 'Tanjong Pagar'],
			        ['code' => 'EW17','en' => 'Tiong Bahru'],
			        ['code' => 'EW18','en' => 'Redhill'],
			        ['code' => 'EW19','en' => 'Queenstown'],
			        ['code' => 'EW20','en' => 'Commonwealth'],
			        ['code' => 'EW20','en' => 'Commonwealth'],
			        ['code' => 'EW21','en' => 'Buona Vista'],
			        ['code' => 'EW22','en' => 'Dover'],
			        ['code' => 'EW23','en' => 'Clementi'],
			        ['code' => 'EW24','en' => 'Jurong East'],
			        ['code' => 'EW25','en' => 'Chinese Garden'],
			        ['code' => 'EW26','en' => 'Lakeside'],
			        ['code' => 'EW26','en' => 'Lakeside'],
			        ['code' => 'EW27','en' => 'Boon Lay'],
			        ['code' => 'EW28','en' => 'Pioneer'],
			        ['code' => 'EW29','en' => 'Joo Koon'],
			        ['code' => 'EW30','en' => 'Gul Circle'],
			        ['code' => 'EW31','en' => 'Tuas Crescent'],
			        ['code' => 'EW32','en' => 'Tuas West Road'],
			        ['code' => 'EW33','en' => 'Tuas Link'],
			        ['code' => 'NE1','en' => 'HarbourFront'],
			        ['code' => 'NE3','en' => 'Outram Park'],
			        ['code' => 'NE4','en' => 'Chinatown'],
			        ['code' => 'NE5','en' => 'Clarke Quay'],
			        ['code' => 'NE6','en' => 'Dhoby Ghaut'],
			        ['code' => 'NE7','en' => 'Little India'],
			        ['code' => 'NE8','en' => 'Farrer Park'],
			        ['code' => 'NE9','en' => 'Boon Keng'],
			        ['code' => 'NE10','en' => 'Potong Pasir'],
			        ['code' => 'NE11','en' => 'Woodleigh'],
			        ['code' => 'NE12','en' => 'Serangoon'],
			        ['code' => 'NE13','en' => 'Kovan'],
			        ['code' => 'NE14','en' => 'Hougang'],
			        ['code' => 'NE15','en' => 'Buangkok'],
			        ['code' => 'NE16','en' => 'Sengkang'],
			        ['code' => 'NE17','en' => 'Punggol'],
			        ['code' => 'NE18','en' => 'Punggol Coast'],
			        ['code' => 'CC1','en' => 'Dhoby Ghaut'],
			        ['code' => 'CC2','en' => 'Bras Basah'],
			        ['code' => 'CC3','en' => 'Esplanade'],
			        ['code' => 'CC4','en' => 'Promenade'],
			        ['code' => 'CC5','en' => 'Nicoll Highway'],
			        ['code' => 'CC6','en' => 'Stadium'],
			        ['code' => 'CC7','en' => 'Mountbatten'],
			        ['code' => 'CC8','en' => 'Dakota'],
			        ['code' => 'CC9','en' => 'Paya Lebar'],
			        ['code' => 'CC10','en' => 'MacPherson'],
			        ['code' => 'CC11','en' => 'Tai Seng'],
			        ['code' => 'CC12','en' => 'Bartley'],
			        ['code' => 'CC13','en' => 'Serangoon'],
			        ['code' => 'CC14','en' => 'Lorong Chuan'],
			        ['code' => 'CC15','en' => 'Bishan'],
			        ['code' => 'CC16','en' => 'Marymount'],
			        ['code' => 'CC17','en' => 'Caldecott'],
			        ['code' => 'CC18','en' => 'Bukit Brown'],
			        ['code' => 'CC19','en' => 'Botanic Gardens'],
			        ['code' => 'CC20','en' => 'Farrer Road'],
			        ['code' => 'CC21','en' => 'Holland Village'],
			        ['code' => 'CC22','en' => 'Buona Vista'],
			        ['code' => 'CC23','en' => 'one-north'],
			        ['code' => 'CC24','en' => 'Kent Ridge'],
			        ['code' => 'CC25','en' => 'Haw Par Villa'],
			        ['code' => 'CC26','en' => 'Pasir Panjang'],
			        ['code' => 'CC27','en' => 'Labrador Park'],
			        ['code' => 'CC28','en' => 'Telok Blangah'],
			        ['code' => 'CC29','en' => 'HarbourFront'],
			        ['code' => 'CC30','en' => 'Keppel'],
			        ['code' => 'CC31','en' => 'Cantonment'],
			        ['code' => 'CC32','en' => 'Prince Edward'],
			        ['code' => 'CE1','en' => 'Bayfront'],
			        ['code' => 'CE2','en' => 'Marina Bay'],
			        ['code' => 'DT1','en' => 'Bukit Panjang'],
			        ['code' => 'DT2','en' => 'Cashew'],
			        ['code' => 'DT3','en' => 'Hillview'],
			        ['code' => 'DT5','en' => 'Beauty World'],
			        ['code' => 'DT6','en' => 'King Albert Park'],
			        ['code' => 'DT7','en' => 'Sixth Avenue'],
			        ['code' => 'DT8','en' => 'Tan Kah Kee'],
			        ['code' => 'DT9','en' => 'Botanic Gardens'],
			        ['code' => 'DT10','en' => 'Stevens'],
			        ['code' => 'DT11','en' => 'Newton'],
			        ['code' => 'DT12','en' => 'Little India'],
			        ['code' => 'DT13','en' => 'Rochor'],
			        ['code' => 'DT14','en' => 'Bugis'],
			        ['code' => 'DT15','en' => 'Promenade'],
			        ['code' => 'DT16','en' => 'Bayfront'],
			        ['code' => 'DT17','en' => 'Downtown'],
			        ['code' => 'DT18','en' => 'Telok Ayer'],
			        ['code' => 'DT19','en' => 'Chinatown'],
			        ['code' => 'DT20','en' => 'Fort Canning'],
			        ['code' => 'DT21','en' => 'Bencoolen'],
			        ['code' => 'DT22','en' => 'Jalan Besar'],
			        ['code' => 'DT23','en' => 'Bendemeer'],
			        ['code' => 'DT24','en' => 'Geylang Bahru'],
			        ['code' => 'DT25','en' => 'Mattar'],
			        ['code' => 'DT26','en' => 'MacPherson'],
			        ['code' => 'DT27','en' => 'Ubi'],
			        ['code' => 'DT28','en' => 'Kaki Bukit'],
			        ['code' => 'DT29','en' => 'Bedok North'],
			        ['code' => 'DT30','en' => 'Bedok Reservoir'],
			        ['code' => 'DT31','en' => 'Tampines West'],
			        ['code' => 'DT32','en' => 'Tampines'],
			        ['code' => 'DT33','en' => 'Tampines East'],
			        ['code' => 'DT34','en' => 'Upper Changi'],
			        ['code' => 'DT35','en' => 'Expo'],
			        ['code' => 'DT36','en' => 'Xilin'],
			        ['code' => 'DT37','en' => 'Sungei Bedok'],
			        ['code' => 'TE1','en' => 'Woodlands North'],
			        ['code' => 'TE2','en' => 'Woodlands'],
			        ['code' => 'TE3','en' => 'Woodlands South'],
			        ['code' => 'TE4','en' => 'Springleaf'],
			        ['code' => 'TE5','en' => 'Lentor'],
			        ['code' => 'TE6','en' => 'Mayflower'],
			        ['code' => 'TE7','en' => 'Bright Hill'],
			        ['code' => 'TE8','en' => 'Upper Thomson'],
			        ['code' => 'TE9','en' => 'Caldecott'],
			        ['code' => 'TE10','en' => 'Mount Pleasant'],
			        ['code' => 'TE11','en' => 'Stevens'],
			        ['code' => 'TE12','en' => 'Napier'],
			        ['code' => 'TE13','en' => 'Orchard Boulevard'],
			        ['code' => 'TE14','en' => 'Orchard'],
			        ['code' => 'TE15','en' => 'Great World'],
			        ['code' => 'TE16','en' => 'Havelock'],
			        ['code' => 'TE17','en' => 'Outram Park'],
			        ['code' => 'TE18','en' => 'Maxwell'],
			        ['code' => 'TE19','en' => 'Shenton Way'],
			        ['code' => 'TE20','en' => 'Marina Bay'],
			        ['code' => 'TE21','en' => 'Marina South'],
			        ['code' => 'TE22','en' => 'Gardens by the Bay'],
			        ['code' => 'TE23','en' => 'Tanjong Rhu'],
			        ['code' => 'TE24','en' => 'Katong Park'],
			        ['code' => 'TE25','en' => 'Tanjong Katong'],
			        ['code' => 'TE26','en' => 'Marine Parade'],
			        ['code' => 'TE27','en' => 'Marine Terrace'],
			        ['code' => 'TE28','en' => 'Siglap'],
			        ['code' => 'TE29','en' => 'Bayshore'],
			        ['code' => 'TE30','en' => 'Bedok South'],
			        ['code' => 'TE31','en' => 'Sungei Bedok'],
			    //Jurong Region Line
			    // 'JRL' => [
			    //     ['code' => 'JS1','en' => 'Choa Chu Kang'],
			    //     ['code' => 'JS2','en' => 'Choa Chu Kang West'],
			    //     ['code' => 'JS3','en' => 'Tengah'],
			    //     ['code' => 'JS4','en' => 'Hong Kah'],
			    //     ['code' => 'JS5','en' => 'Corporation'],
			    //     ['code' => 'JS6','en' => 'Jurong West'],
			    //     ['code' => 'JS7','en' => 'Bahar Junction'],
			    //     ['code' => 'JS8','en' => 'Boon Lay'],
			    //     ['code' => 'JS9','en' => 'Enterprise'],
			    //     ['code' => 'JS10','en' => 'Tukang'],
			    //     ['code' => 'JS11','en' => 'Jurong Hill'],
			    //     ['code' => 'JS12','en' => 'Jurong Pier'],
			    //     ['code' => 'JW1','en' => 'Gek Poh'],
			    //     ['code' => 'JW2','en' => 'Tawas'],
			    //     ['code' => 'JW3','en' => 'Nanyang Gateway'],
			    //     ['code' => 'JW4','en' => 'Nanyang Crescent'],
			    //     ['code' => 'JW5','en' => 'Peng Kang Hill'],
			    //     ['code' => 'JE1','en' => 'Tengah Plantation'],
			    //     ['code' => 'JE2','en' => 'Tengah Park'],
			    //     ['code' => 'JE3','en' => 'Bukit Batok West'],
			    //     ['code' => 'JE4','en' => 'Toh Guan'],
			    //     ['code' => 'JE5','en' => 'Jurong East'],
			    //     ['code' => 'JE6','en' => 'Jurong Town Hall'],
			    //     ['code' => 'JE7','en' => 'Pandan Reservoir'],
			    // ]
			];
}
